server:
  port: 10000
  listen: true
  cors: true
  disable_csrf: true
  basic_auth: false
  autorun: true
  cookie_secret_file: data/cookie-secret.txt

debug: true
allow_all_ips: true
whitelist_mode: false

model:
  provider: mistral
  endpoint: https://api.mistral.ai/v1/chat/completions
  api_key: /etc/secrets/sam_heal_mistral_api
  model_name: mistral-7b-instruct
